name: "JuicePassProxy Auto Register Devices"
description: "This tool will publish JuiceBox data to Home Assistant by using a Man in the Middle UDP proxy to MQTT that is auto-discoverable by HomeAssistant."
version: "0.5.1.16"
slug: "juicepassproxy"
image: "ghcr.io/azlinon/hassio-juicepassproxy"
ports:
  "8042/udp": 8042
panel_icon: mdi:ev-station
arch:
  - aarch64
  - amd64
discovery:
  - mqtt
services:
  - "mqtt:need"
options:
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  jpp_host: ""
  enelx_ip: "54.161.185.130"
  local_port: 8042
schema:
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str
  mqtt_password: password
  jpp_host: str
  experimental: bool?
  debug: bool?
  enelx_ip: str?
  local_port: port?
